### ISSUE TITLE
[M0] ¿Qué estructura se necesita en una tarea?

### ISSUE THREAD

**Issue by javigp2002** [Christianlr/MIBarberSchedule#10]
Las tareas suelen tener un sentido único y, aunque no se como se añadirán de forma dinámica, pueden repetirse pero serán nuevas tareas. Entiendo que podemos asignarle:

- ~~id~~: No existe id en objeto-valor
- nombreTarea o Título
- TiempoEstimado (que yo pondría en minutos)
- fechaCreacion: Date
- Prioridad

La última nos servirá para poder crear una prioridad por fecha de creación más antigua. Asimismo, estamos dejando un objeto-valor tarea cuya información no ses modifica normalmente. ¿Qué te parece? ¿Añadirías algo?

**Comment by Christianlr** [comment]
Diría que la fecha de creación, como comentas, es el punto más importante de la Tarea en si para determinar su prioridad. No faltaría nada a mi parecer, está perfecto :sunglasses:

**Comment by JJ** [comment]
Algo que falta aquí es decidir qué unidad vas a usar para todos los tiempos. En https://github.com/Christianlr/MIBarberSchedule/commit/e1c40dcae8475dee5f437ef9b46de238e7cb51d8 has resuelto un comentario, pero no has tenido en cuenta que tendrías que resolverlo con respecto al issue planteado. En parte culpa mía, porque no te dije muy claramente que las soluciones tienen siempre que venir informadas por los problemas que hayas planteado, pero ahora veo que tendrías que clarificar este issue y su relación con quizás #12 simplemente para que todos los tiempos que se usen en las diferentes partes del modelo sean los mismos.
