### ISSUE TITLE
[M0] ¿Qué agenda tienen que seguir los barberos?

### ISSUE THREAD

**Issue by javigp2002** [Christianlr/MIBarberSchedule#11]
La agenda de un barbero imagino que es lo que estos siguen para conocer qué tienen que hacer durante la semana. Por ello, esta clase es la más complicada y ambigua si queremos una buena estructura de datos. Por ello, es necesario conocer los datos básicos y necesarios de una agenda que viene a ser:

- Tareas
- Tiempo libre de trabajadores

**Comment by Christianlr** [comment]
Vale! reviso los demás issues! :smiley:

**Comment by Christianlr** [comment]
He revisado los issues y todo está correcto la verdad. Se presenta una buena estructura en cuanto a los distintos datos que se presentan dentro del dominio del problema. Pienso que no has dejado nada fuera y está todo muy bien recogido :+1:

**Comment by javigp2002** [comment]
He modificado el cuerpo del issue para que se adecúe más a un issue.
