### ISSUE TITLE
[M0] ¿Qué se considera tiempo libre en trabajadores?

### ISSUE THREAD

**Issue by javigp2002** [Christianlr/MIBarberSchedule#12]
El tiempo libre de un trabajador debe de estar predeterminado y conocer ya cuando existen estos intervalos a priori ya que estos serán todos aquellos momentos que se encuentren en su horario laboral pero no trabajando y para saber esto deberás tener alguna información que recopile cuales son los tiempos que se encuentran pelando.

Por tanto, el intervalo del tiempo se tendrá que asignar a cada trabajador para que puedan existir tiempos donde varios trabajadores estén libres a la vez, también podremos coger parte de ese intervalo de tiempo según se necesite en una tarea.

**Comment by Christianlr** [comment]
Entiendo que en ese intervalo de tiempo es completo. Lo veo muy bien ya que se puede trabajar correctamente con los trabajadores y sus correspondientes tiempos libres según ellos lo registren como tal

**Comment by javigp2002** [comment]
Dándole otra vuelta, tendríamos también que añadir al intervalo de tiempo (si lo estamos haciendo por cada semana), otra variable que fuera el día de la semana.

**Comment by javigp2002** [comment]
He modificado el cuerpo del issue, echale un vistazo si puedes :smiley:.
