### ISSUE TITLE
[M0] ¿Existen tareas predeterminadas?

### ISSUE THREAD

**Issue by javigp2002** [Christianlr/MIBarberSchedule#15]
Añadiendo información al #10 la existencia de tareas predeterminadas puede ser importante para tener en cuenta de cara a este milestone.

**Comment by javigp2002** [comment]
Como hemos llegado a la conclusión en clase, lo dejo escrito. Finalmente, una tarea no tiene que existir de forma predeterminada porque, aunque es posible que muchas se repitan a lo largo del tiempo, es decir, no siempre barrer dura lo mismo dependerá de la cantidad de personas que se hayan cortado el pelo.

**Comment by Christianlr** [comment]
@javigp2002 Totalmente de acuerdo, además, ese ejemplo que mencionas muestra que no tendría mucho sentido que una tarea exista de forma predeterminada.
