### ISSUE TITLE
[M0] ¿Cómo reprensentamos la prioridad de una tarea?

### ISSUE THREAD

**Issue by javigp2002** [Christianlr/MIBarberSchedule#17]
Siguiendo la cuestión del #10.
La prioridad de una tarea nos sirve para poner en orden y por orden de importancia todas las tareas que tengamos así como según la fecha de creación. Se podrían dividir las prioridades en:
 - ALTA
 - MEDIA
 - BAJA
Ya será el encargado de crear la tarea el que decida su prioridad.

**Comment by javigp2002** [comment]
Esto es según lo comentado en clase, ya me dices @Christianlr  :construction:

**Comment by Christianlr** [comment]
@javigp2002 Exactamente, siguiendo lo que hemos comentado en clase, las tareas tendrán una prioridad que, a su vez junto con la fecha de creación de dicha tarea, se determinará qué tarea será planificada antes que otras :heavy_check_mark: :smile:
