### ISSUE TITLE
Elección del lenguaje de programación

### ISSUE THREAD

**Issue by javigp2002** [Christianlr/MIBarberSchedule#6]
Buenas, se me ha asignado este repositorio para el objetivo 2. Para la elección del lenguaje de programación escogeria entre **JavaScript** o **TypeScript** pero teniendo en cuenta lo comentado por el profesor en clase elegiría un lenguaje tipado (permitiendo variables privadas ) que sirva tanto para BackEnd como FrontEnd.

**Comment by Christianlr** [comment]
Buenas @javigp2002! Pensé justo en hacerlo en un lenguaje u otro pero creo que `TypeScript` puede ser interesante para el desarrollo del proyecto ya que nunca he trabajado con él. Considero que sería buena idea aprenderlo.
