### ISSUE TITLE
[M0] Propuesta de Estructura de datos

### ISSUE THREAD

**Issue by javigp2002** [Christianlr/MIBarberSchedule#8]
Buenas @Christianlr, he estado pensando acerca del proyecto y había pensado organizarlo de la siguiente manera (espero que sea más o menos lo que tenías pensado).

 ## Clase trabajador
- ~~Básicamente esta va a representar al trabajador con su información personal (DNI, nombre y apellido) según he podido entender del #2~~
_No es necesaria por lo que se ha comentado en #9_

## Clase tarea
- En esta representaremos una tarea y su características básicas como pueden ser: titulo o nombre y tiempo estimado. También había pensado en si se pueden pausar pero como no se menciona te dejo esto por si quieres...

## Clase agenda
- Esta tendremos que verla más detalladamente, siempre que te parezca bien la ED. En principio, unirían todas las tareas con los trabajadores y sus tiempos libres.

Espero tu respuesta 😄

**Comment by Christianlr** [comment]
Buenas @javigp2002! Pues es tal y como lo tenía yo pensado! Veo que coincidimos bastante. Hay una cosa que quizás se escape o pienso que no es necesario, aunque no deja de ser una buena idea para un desarrollo más completo. Me refiero al tema de 'pausar las tareas'. Creo que sería ahora mismo idóneo simplemente tener en cuenta qué tareas han sido realizadas o no. Que te parece? Por lo demás, insisto, lo veo súper bien! :ok_hand: :sunglasses:
