### ISSUE TITLE
[M0] ¿Cuales son los datos del usuario?

### ISSUE THREAD

**Issue by javigp2002** [Christianlr/MIBarberSchedule#9]
Según la #2 realmente no necesitamos más datos de un barbero que:
- Nombre
- Apellidos
- DNI (Solo números)
Si fuera necesario algo más me gustaría que me lo plantearas 😄

**Comment by Christianlr** [comment]
Exacto, es una estructura muy buena ya que se recogen los datos necesarios de los barberos :+1:

**Comment by javigp2002** [comment]
Finalmente, según lo hablado con JJ en clase, los datos de usuario no serían un problema debido a que solo tenemos que poder identificar a las personas para asignar y esto se puede hacer con identificadores básicos.
